Repository brain-tec/delivery-carrier, pull requests merged in 2021-03, with the labels that each got.

#223 [t120961] NETA V13: TEST-MERGE New Postlogistics Connector Based on OCA Delivery Carrier
  delivery_postlogistics/README.rst
  delivery_postlogistics/__init__.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/data/barcode handbuch.PDF
  delivery_postlogistics/data/delivery.xml
  delivery_postlogistics/data/partner.xml
  delivery_postlogistics/data/product.xml
  delivery_postlogistics/models/__init__.py
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_license.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/product_packaging.py
  delivery_postlogistics/models/res_partner.py
  delivery_postlogistics/models/stock_move.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/models/stock_quant_package.py
  delivery_postlogistics/postlogistics/__init__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/readme/CONFIGURE.rst
  delivery_postlogistics/readme/CONTRIBUTORS.rst
  delivery_postlogistics/readme/CREDITS.rst
  delivery_postlogistics/readme/DESCRIPTION.rst
  delivery_postlogistics/readme/INSTALL.rst
  delivery_postlogistics/readme/ROADMAP.rst
  delivery_postlogistics/security/ir.model.access.csv
  delivery_postlogistics/static/description/icon.svg
  delivery_postlogistics/static/description/index.html
  delivery_postlogistics/static/img/postlogistics-logo.jpg
  delivery_postlogistics/tests/__init__.py
  delivery_postlogistics/tests/fixtures/cassettes/test_missing_language.yaml
  delivery_postlogistics/tests/fixtures/cassettes/test_store_label.yaml
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/views/delivery.xml
  delivery_postlogistics/views/postlogistics_license.xml
  delivery_postlogistics/views/res_partner_view.xml
  delivery_postlogistics/views/stock.xml
  delivery_postlogistics/views/stock_quant_package_view.xml
  requirements.txt
  setup/delivery_postlogistics/odoo/addons/delivery_postlogistics
  setup/delivery_postlogistics/setup.py
Labels: 13.0.project_mi_465

#226 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: 13.0

#225 [t120598] DHL Business Customer Shipping API Based on OCA Delivery Carrier
  delivery_dhl_de/README.rst
  delivery_dhl_de/__init__.py
  delivery_dhl_de/__manifest__.py
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1-schema-bcs_base.xsd
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1-schema-cis_base.xsd
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1.wsdl
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/product_packaging.py
  delivery_dhl_de/models/res_partner.py
  delivery_dhl_de/models/stock_picking.py
  delivery_dhl_de/views/delivery_carrier.xml
  delivery_dhl_de/views/stock_picking_views.xml
  delivery_dhl_de/views/view_res_partner.xml
Labels: 13.0.project_mi_465

#228 Syncing from upstream OCA/delivery-carrier (13.0)
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: 13.0

#229 Syncing from upstream OCA/delivery-carrier (13.0)
  partner_delivery_zone/i18n/fr_FR.po
Labels: 13.0

#230 Updating from latest OCA 13.0
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: 13.0.project_mi_465

#231 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_postlogistics/models/stock.py
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: 12.0
