Repository brain-tec/delivery-carrier, pull requests merged in 2021-11, with the labels that each got.

#349 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/i18n/delivery_carrier_label_ups.pot
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: 12.0

#350 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_partner/README.rst
  delivery_carrier_partner/__init__.py
  delivery_carrier_partner/__manifest__.py
  delivery_carrier_partner/i18n/delivery_carrier_partner.pot
  delivery_carrier_partner/i18n/it.po
  delivery_carrier_partner/models/__init__.py
  delivery_carrier_partner/models/delivery_carrier.py
  delivery_carrier_partner/readme/CONTRIBUTORS.rst
  delivery_carrier_partner/readme/DESCRIPTION.rst
  delivery_carrier_partner/static/description/icon.png
  delivery_carrier_partner/static/description/index.html
  delivery_carrier_partner/views/delivery_carrier_views.xml
  delivery_package_fee/__manifest__.py
  delivery_package_fee/i18n/delivery_package_fee.pot
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/views/delivery_carrier_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_partner/odoo/addons/delivery_carrier_partner
  setup/delivery_carrier_partner/setup.py
  setup/stock_picking_carrier_from_rule/odoo/addons/stock_picking_carrier_from_rule
  setup/stock_picking_carrier_from_rule/setup.py
  stock_picking_carrier_from_rule/README.rst
  stock_picking_carrier_from_rule/__init__.py
  stock_picking_carrier_from_rule/__manifest__.py
  stock_picking_carrier_from_rule/i18n/stock_picking_carrier_from_rule.pot
  stock_picking_carrier_from_rule/models/__init__.py
  stock_picking_carrier_from_rule/models/stock_move.py
  stock_picking_carrier_from_rule/readme/CONTRIBUTORS.rst
  stock_picking_carrier_from_rule/readme/CREDITS.rst
  stock_picking_carrier_from_rule/readme/DESCRIPTION.rst
  stock_picking_carrier_from_rule/readme/ROADMAP.rst
  stock_picking_carrier_from_rule/static/description/icon.png
  stock_picking_carrier_from_rule/static/description/index.html
Labels: 14.0

#351 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
Labels: 13.0

#352 Syncing from upstream OCA/delivery-carrier (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 13.0

#353 Syncing from upstream OCA/delivery-carrier (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 14.0

#354 Syncing from upstream OCA/delivery-carrier (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
Labels: 15.0

#355 Updating from latest OCA 13.0
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  CONTRIBUTING.md
  README.md
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
Labels: 13.0.project_mi_465

#357 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/i18n/delivery_carrier_label_ups.pot
  delivery_carrier_label_ups/models/carrier_account.py
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
  delivery_carrier_label_ups/views/carrier_account.xml
Labels: 12.0

#358 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0

#359 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  partner_default_delivery_carrier/README.rst
  partner_default_delivery_carrier/__init__.py
  partner_default_delivery_carrier/__manifest__.py
  partner_default_delivery_carrier/i18n/partner_default_delivery_carrier.pot
  partner_default_delivery_carrier/models/__init__.py
  partner_default_delivery_carrier/models/res_config_settings.py
  partner_default_delivery_carrier/readme/CONFIGURE.rst
  partner_default_delivery_carrier/readme/CONTRIBUTORS.rst
  partner_default_delivery_carrier/readme/DESCRIPTION.rst
  partner_default_delivery_carrier/static/description/icon.png
  partner_default_delivery_carrier/static/description/index.html
  partner_default_delivery_carrier/tests/__init__.py
  partner_default_delivery_carrier/tests/test_default_delivery_carrier.py
  partner_default_delivery_carrier/views/res_config_settings.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_default_delivery_carrier/odoo/addons/partner_default_delivery_carrier
  setup/partner_default_delivery_carrier/setup.py
Labels: 14.0

#361 Merging 13.0 into 13.0.project_MI_465
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465

#362 Merging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465.test
