Repository brain-tec/delivery-carrier, pull requests merged in 2021-04, with the labels that each got.

#238 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0

#240 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_send_to_shipper_at_operation/README.rst
  delivery_send_to_shipper_at_operation/__init__.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  delivery_send_to_shipper_at_operation/i18n/delivery_send_to_shipper_at_operation.pot
  delivery_send_to_shipper_at_operation/models/__init__.py
  delivery_send_to_shipper_at_operation/models/delivery_carrier.py
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/readme/CONTRIBUTORS.rst
  delivery_send_to_shipper_at_operation/readme/DESCRIPTION.rst
  delivery_send_to_shipper_at_operation/readme/ROADMAP.rst
  delivery_send_to_shipper_at_operation/readme/USAGE.rst
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier1.png
  delivery_send_to_shipper_at_operation/static/description/delivery_carrier2.png
  delivery_send_to_shipper_at_operation/static/description/icon.png
  delivery_send_to_shipper_at_operation/static/description/index.html
  delivery_send_to_shipper_at_operation/tests/__init__.py
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
  delivery_send_to_shipper_at_operation/views/delivery_carrier.xml
  delivery_send_to_shipper_at_operation/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_send_to_shipper_at_operation/odoo/addons/delivery_send_to_shipper_at_operation
  setup/delivery_send_to_shipper_at_operation/setup.py
Labels: 13.0

#243 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_package_fee/README.rst
  delivery_package_fee/__init__.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/i18n/delivery_package_fee.pot
  delivery_package_fee/models/__init__.py
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/models/stock_picking.py
  delivery_package_fee/readme/CONFIGURE.rst
  delivery_package_fee/readme/CONTRIBUTORS.rst
  delivery_package_fee/readme/DESCRIPTION.rst
  delivery_package_fee/security/ir.model.access.csv
  delivery_package_fee/static/description/icon.png
  delivery_package_fee/static/description/index.html
  delivery_package_fee/tests/__init__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_package_fee/views/delivery_carrier_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_package_fee/odoo/addons/delivery_package_fee
  setup/delivery_package_fee/setup.py
Labels: 14.0

#245 [bt#14232] [NETA V13 Prod] DHL Connector: No Tracking Mail to Customer
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test

#244 [bt#14232] [NETA V13 Prod] DHL Connector: No Tracking Mail to Customer
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465

#247 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_state/i18n/nl.po
  partner_delivery_schedule/i18n/nl.po
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
Labels: 13.0

#250 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/DESCRIPTION.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/static/description/icon.png
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/views/sale_order_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_auto_refresh/odoo/addons/delivery_auto_refresh
  setup/delivery_auto_refresh/setup.py
Labels: 13.0
