Repository brain-tec/delivery-carrier, pull requests merged in 2021-06, with the labels that each got.

#269 [bt#14449] DHL connector SO prevent order validation on error
  delivery_dhl_de/__manifest__.py
  delivery_dhl_de/models/__init__.py
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/sale_order.py
  delivery_dhl_de/models/stock_picking.py
  delivery_dhl_de/views/sale_order_views.xml
  delivery_dhl_de/views/stock_picking_views.xml
Labels: 13.0, 13.0.project_mi_465, feature

#271 [bt#14449] Back-merge from 13.0.project_MI_465 to 13.0.project_MI_465.test
  delivery_dhl_de/__manifest__.py
  delivery_dhl_de/models/__init__.py
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/sale_order.py
  delivery_dhl_de/models/stock_picking.py
  delivery_dhl_de/views/sale_order_views.xml
  delivery_dhl_de/views/stock_picking_views.xml
Labels: 13.0.project_mi_465.test

#272 Fixing errors about pre-commit in project branch
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/sale_order.py
  delivery_dhl_de/views/sale_order_views.xml
Labels: 13.0.project_mi_465

#270 Updating from latest OCA 13.0
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_carrier_info/i18n/es.po
Labels: 13.0.project_mi_465

#274 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/common.py
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: 13.0

#275 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/models/stock_picking.py
Labels: 13.0

#277 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: 12.0

#278 Backmerging 13.0 into 13.0.project_MI_465
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/common.py
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: 13.0.project_mi_465

#279 Backmerging 13.0.project_MI_456 into 13.0.project_MI_456.test
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_carrier_info/i18n/es.po
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/sale_order.py
  delivery_dhl_de/views/sale_order_views.xml
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/common.py
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: 13.0.project_mi_465.test

#273 [bt#14790] FIX: Adding positional argument in call
  delivery_dhl_de/models/delivery_carrier.py
Labels: 13.0.project_mi_465

#280 Backmerging 13.0.project_MI_465 into 13.0.project_MI_465.test
  delivery_dhl_de/models/delivery_carrier.py
Labels: 13.0.project_mi_465.test

#282 [bt#15025] Fixed Packstation handling when generating labels, added tracking to dhl
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test

#283 [bt#15025] Fixed issue of a lower() that could happen over a non exitent street2 value
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test, bug

#284 [bt#15025] Changed where the packstation word is looked for when creating the request for DHL labels
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test
