Repository brain-tec/delivery-carrier, pull requests merged in 2021-12, with the labels that each got.

#363 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_location/README.rst
  delivery_carrier_location/__init__.py
  delivery_carrier_location/__manifest__.py
  delivery_carrier_location/i18n/delivery_carrier_location.pot
  delivery_carrier_location/models/__init__.py
  delivery_carrier_location/models/delivery_carrier.py
  delivery_carrier_location/readme/CONTRIBUTORS.rst
  delivery_carrier_location/readme/DESCRIPTION.rst
  delivery_carrier_location/static/description/icon.png
  delivery_carrier_location/static/description/index.html
  delivery_carrier_location/tests/__init__.py
  delivery_carrier_location/tests/test_delivery_carrier_location.py
  delivery_carrier_location/views/delivery_carrier.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_location/odoo/addons/delivery_carrier_location
  setup/delivery_carrier_location/setup.py
Labels: 14.0

#364 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0

#365 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_agency/README.rst
  delivery_carrier_agency/__init__.py
  delivery_carrier_agency/__manifest__.py
  delivery_carrier_agency/i18n/delivery_carrier_agency.pot
  delivery_carrier_agency/models/__init__.py
  delivery_carrier_agency/models/delivery_carrier_agency.py
  delivery_carrier_agency/models/stock_picking.py
  delivery_carrier_agency/readme/CONTRIBUTORS.rst
  delivery_carrier_agency/readme/DESCRIPTION.rst
  delivery_carrier_agency/security/ir.model.access.csv
  delivery_carrier_agency/static/description/icon.png
  delivery_carrier_agency/static/description/index.html
  delivery_carrier_agency/tests/__init__.py
  delivery_carrier_agency/tests/test_carrier_agency.py
  delivery_carrier_agency/views/delivery_carrier_agency_view.xml
  delivery_carrier_default_tracking_url/README.rst
  delivery_carrier_default_tracking_url/__init__.py
  delivery_carrier_default_tracking_url/__manifest__.py
  delivery_carrier_default_tracking_url/i18n/delivery_carrier_default_tracking_url.pot
  delivery_carrier_default_tracking_url/models/__init__.py
  delivery_carrier_default_tracking_url/models/delivery_carrier.py
  delivery_carrier_default_tracking_url/models/sale_order.py
  delivery_carrier_default_tracking_url/models/stock_picking.py
  delivery_carrier_default_tracking_url/readme/CONTRIBUTORS.rst
  delivery_carrier_default_tracking_url/readme/DESCRIPTION.rst
  delivery_carrier_default_tracking_url/readme/USAGE.rst
  delivery_carrier_default_tracking_url/static/description/icon.png
  delivery_carrier_default_tracking_url/static/description/index.html
  delivery_carrier_default_tracking_url/views/delivery_carrier.xml
  delivery_carrier_default_tracking_url/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_agency/odoo/addons/delivery_carrier_agency
  setup/delivery_carrier_agency/setup.py
  setup/delivery_carrier_default_tracking_url/odoo/addons/delivery_carrier_default_tracking_url
  setup/delivery_carrier_default_tracking_url/setup.py
Labels: 14.0

#366 Merging 13.0 into 13.0.project_MI_465
  README.md
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465

#367 Merging 13.0.project_mi_465 into 13.0.project_mi_465.test
  README.md
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465.test

#368 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_schenker/README.rst
  delivery_schenker/__init__.py
  delivery_schenker/__manifest__.py
  delivery_schenker/api/fat_bookingWebServiceV1_1.wsdl
  delivery_schenker/api/prod_bookingWebServiceV1_1.wsdl
  delivery_schenker/data/delivery_schenker_data.xml
  delivery_schenker/i18n/delivery_schenker.pot
  delivery_schenker/models/__init__.py
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/models/product_packaging.py
  delivery_schenker/models/schenker_request.py
  delivery_schenker/readme/CONFIGURE.rst
  delivery_schenker/readme/CONTRIBUTORS.rst
  delivery_schenker/readme/DESCRIPTION.rst
  delivery_schenker/readme/INSTALL.rst
  delivery_schenker/readme/ROADMAP.rst
  delivery_schenker/readme/USAGE.rst
  delivery_schenker/static/description/icon.png
  delivery_schenker/static/description/icon.svg
  delivery_schenker/static/description/index.html
  delivery_schenker/tests/__init__.py
  delivery_schenker/views/delivery_schenker_view.xml
  delivery_schenker/views/stock_picking_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_schenker/odoo/addons/delivery_schenker
  setup/delivery_schenker/setup.py
Labels: 13.0

#369 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_correos_express/README.rst
  delivery_correos_express/__init__.py
  delivery_correos_express/__manifest__.py
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_ apiRestSeguimientoEnviosk8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_GrabacionEnviosRest_v03.07.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_ListEnviosRest_v01.01.pdf
  delivery_correos_express/doc/GrabacionEnvios/DC_SP_WS_apiRestEtiquetaTransporte_v01.01.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_Seguimiento_Recogidak8s_v01.00.pdf
  delivery_correos_express/doc/GrabacionRecogidas/DC_SP_WS_GrabacionRecogidaRest_v1.4.pdf
  delivery_correos_express/i18n/delivery_correos_express.pot
  delivery_correos_express/i18n/es.po
  delivery_correos_express/models/__init__.py
  delivery_correos_express/models/correos_express_request.py
  delivery_correos_express/models/delivery_carrier.py
  delivery_correos_express/models/stock_picking.py
  delivery_correos_express/readme/CONFIGURE.rst
  delivery_correos_express/readme/CONTRIBUTORS.rst
  delivery_correos_express/readme/DESCRIPTION.rst
  delivery_correos_express/readme/INSTALL.rst
  delivery_correos_express/readme/ROADMAP.rst
  delivery_correos_express/readme/USAGE.rst
  delivery_correos_express/static/description/icon.png
  delivery_correos_express/static/description/index.html
  delivery_correos_express/tests/__init__.py
  delivery_correos_express/tests/test_delivery_correos_express.py
  delivery_correos_express/views/delivery_carrier_view.xml
  delivery_correos_express/views/stock_picking_views.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_correos_express/odoo/addons/delivery_correos_express
  setup/delivery_correos_express/setup.py
Labels: 14.0

#370 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_schenker/__manifest__.py
  delivery_schenker/i18n/delivery_schenker.pot
  delivery_schenker/views/stock_picking_views.xml
  delivery_tnt_oca/README.rst
  delivery_tnt_oca/__init__.py
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Pricing Integration Guide v3 Schema.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Shipping Integration Guide v3.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect_Tracking_V3_1.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel Integration Guide v1.10.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel_Integration Guide_Arrangements.pdf
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/__init__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/product_packaging.py
  delivery_tnt_oca/models/stock_picking.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/readme/CONFIGURE.rst
  delivery_tnt_oca/readme/CONTRIBUTORS.rst
  delivery_tnt_oca/readme/DESCRIPTION.rst
  delivery_tnt_oca/readme/ROADMAP.rst
  delivery_tnt_oca/readme/USAGE.rst
  delivery_tnt_oca/report/picking_templates.xml
  delivery_tnt_oca/report/stock_report_views.xml
  delivery_tnt_oca/static/description/icon.png
  delivery_tnt_oca/static/description/index.html
  delivery_tnt_oca/tests/__init__.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_tnt_oca/odoo/addons/delivery_tnt_oca
  setup/delivery_tnt_oca/setup.py
Labels: 13.0

#371 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_schenker/README.rst
  delivery_schenker/__init__.py
  delivery_schenker/__manifest__.py
  delivery_schenker/api/fat_bookingWebServiceV1_1.wsdl
  delivery_schenker/api/fat_trackingWebServiceV2.wsdl
  delivery_schenker/api/prod_bookingWebServiceV1_1.wsdl
  delivery_schenker/api/prod_trackingWebServiceV2.wsdl
  delivery_schenker/data/delivery_schenker_data.xml
  delivery_schenker/i18n/delivery_schenker.pot
  delivery_schenker/i18n/es.po
  delivery_schenker/models/__init__.py
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/models/product_packaging.py
  delivery_schenker/models/schenker_request.py
  delivery_schenker/models/stock_picking.py
  delivery_schenker/readme/CONFIGURE.rst
  delivery_schenker/readme/CONTRIBUTORS.rst
  delivery_schenker/readme/DESCRIPTION.rst
  delivery_schenker/readme/INSTALL.rst
  delivery_schenker/readme/ROADMAP.rst
  delivery_schenker/readme/USAGE.rst
  delivery_schenker/static/description/icon.png
  delivery_schenker/static/description/icon.svg
  delivery_schenker/static/description/index.html
  delivery_schenker/tests/__init__.py
  delivery_schenker/views/delivery_schenker_view.xml
  delivery_schenker/views/stock_picking_views.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_schenker/odoo/addons/delivery_schenker
  setup/delivery_schenker/setup.py
Labels: 14.0

#373 Syncing from upstream OCA/delivery-carrier (10.0)
  README.md
  delivery_carrier_label_default/README.rst
  delivery_carrier_label_default/__init__.py
  delivery_carrier_label_default/__manifest__.py
  delivery_carrier_label_default/i18n/delivery_carrier_label_default.pot
  delivery_carrier_label_default/models/__init__.py
  delivery_carrier_label_default/models/stock_picking.py
  delivery_carrier_label_default/reports/report_default_label.xml
  delivery_carrier_label_default/reports/report_paper_format.xml
  delivery_carrier_label_default/static/description/icon.svg
  delivery_carrier_label_default/tests/__init__.py
  delivery_carrier_label_default/tests/test_print_label.py
  delivery_carrier_label_default_webkit/__init__.py
  delivery_carrier_label_default_webkit/report/__init__.py
  delivery_carrier_label_default_webkit/report/shipping_label_report.py
  delivery_carrier_label_default_webkit/report/template/shipping_label.mako
  delivery_carrier_label_default_webkit/reports.xml
  delivery_carrier_label_default_webkit/stock.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_label_default/odoo/__init__.py
  setup/delivery_carrier_label_default/odoo/addons/__init__.py
  setup/delivery_carrier_label_default/odoo/addons/delivery_carrier_label_default
  setup/delivery_carrier_label_default/setup.py
Labels: 10.0
