Repository brain-tec/delivery-carrier, pull requests merged in 2021-08, with the labels that each got.

#297 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_price_rule_volumetric_weight/README.rst
  delivery_price_rule_volumetric_weight/__init__.py
  delivery_price_rule_volumetric_weight/__manifest__.py
  delivery_price_rule_volumetric_weight/i18n/delivery_price_rule_volumetric_weight.pot
  delivery_price_rule_volumetric_weight/i18n/es.po
  delivery_price_rule_volumetric_weight/models/__init__.py
  delivery_price_rule_volumetric_weight/models/delivery_carrier.py
  delivery_price_rule_volumetric_weight/models/delivery_price_rule.py
  delivery_price_rule_volumetric_weight/readme/CONFIGURE.rst
  delivery_price_rule_volumetric_weight/readme/CONTRIBUTORS.rst
  delivery_price_rule_volumetric_weight/readme/DESCRIPTION.rst
  delivery_price_rule_volumetric_weight/readme/USAGE.rst
  delivery_price_rule_volumetric_weight/static/description/icon.png
  delivery_price_rule_volumetric_weight/static/description/index.html
  delivery_price_rule_volumetric_weight/tests/__init__.py
  delivery_price_rule_volumetric_weight/tests/test_delivery_price.py
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_price_rule_volumetric_weight/odoo/addons/delivery_price_rule_volumetric_weight
  setup/delivery_price_rule_volumetric_weight/setup.py
Labels: 13.0

#298 Syncing from upstream OCA/delivery-carrier (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  base_delivery_carrier_label/tests/test_send.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  stock_picking_delivery_link/__manifest__.py
Labels: 13.0

#299 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_paazl/__manifest__.py
  delivery_carrier_label_paazl/i18n/delivery_carrier_label_paazl.pot
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_paazl/tests/test_delivery_carrier_label_paazl.py
  delivery_carrier_label_ups/README.rst
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/i18n/delivery_carrier_label_ups.pot
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/readme/ROADMAP.rst
  delivery_carrier_label_ups/static/description/index.html
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: 12.0

#300 Syncing from upstream OCA/delivery-carrier (8.0)
  README.md
Labels: 8.0

#301 Syncing from upstream OCA/delivery-carrier (9.0)
  README.md
Labels: 9.0

#302 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
Labels: 13.0

#303 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
Labels: 14.0

#304 Syncing from upstream OCA/delivery-carrier (10.0)
  README.md
Labels: 10.0

#305 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_roulier_laposte_fr/__manifest__.py
  delivery_roulier_laposte_fr/i18n/delivery_roulier_laposte_fr.pot
  delivery_roulier_laposte_fr/tests/test_laposte_label_dom.py
Labels: 14.0

#306 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_pricelist/README.rst
  delivery_carrier_pricelist/__init__.py
  delivery_carrier_pricelist/__manifest__.py
  delivery_carrier_pricelist/i18n/delivery_carrier_pricelist.pot
  delivery_carrier_pricelist/models/__init__.py
  delivery_carrier_pricelist/models/delivery_carrier.py
  delivery_carrier_pricelist/models/stock_picking.py
  delivery_carrier_pricelist/readme/CONTRIBUTORS.rst
  delivery_carrier_pricelist/readme/CREDITS.rst
  delivery_carrier_pricelist/readme/DESCRIPTION.rst
  delivery_carrier_pricelist/security/ir.model.access.csv
  delivery_carrier_pricelist/static/description/icon.png
  delivery_carrier_pricelist/static/description/index.html
  delivery_carrier_pricelist/tests/__init__.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
  delivery_carrier_pricelist/wizards/__init__.py
  delivery_carrier_pricelist/wizards/choose_delivery_carrier.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_pricelist/odoo/addons/delivery_carrier_pricelist
  setup/delivery_carrier_pricelist/setup.py
Labels: 14.0

#307 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_paazl/__manifest__.py
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
Labels: 12.0

#308 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
Labels: 14.0

#309 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONTRIBUTORS.rst
  partner_delivery_zone/readme/DESCRIPTION.rst
  partner_delivery_zone/readme/ROADMAP.rst
  partner_delivery_zone/readme/USAGE.rst
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_delivery_zone/odoo/addons/partner_delivery_zone
  setup/partner_delivery_zone/setup.py
Labels: 14.0

#310 Update from latest OCA 13.0
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  base_delivery_carrier_label/tests/test_send.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/stock_picking.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
  delivery_price_rule_volumetric_weight/README.rst
  delivery_price_rule_volumetric_weight/__init__.py
  delivery_price_rule_volumetric_weight/__manifest__.py
  delivery_price_rule_volumetric_weight/i18n/delivery_price_rule_volumetric_weight.pot
  delivery_price_rule_volumetric_weight/i18n/es.po
  delivery_price_rule_volumetric_weight/models/__init__.py
  delivery_price_rule_volumetric_weight/models/delivery_carrier.py
  delivery_price_rule_volumetric_weight/models/delivery_price_rule.py
  delivery_price_rule_volumetric_weight/readme/CONFIGURE.rst
  delivery_price_rule_volumetric_weight/readme/CONTRIBUTORS.rst
  delivery_price_rule_volumetric_weight/readme/DESCRIPTION.rst
  delivery_price_rule_volumetric_weight/readme/USAGE.rst
  delivery_price_rule_volumetric_weight/static/description/icon.png
  delivery_price_rule_volumetric_weight/static/description/index.html
  delivery_price_rule_volumetric_weight/tests/__init__.py
  delivery_price_rule_volumetric_weight/tests/test_delivery_price.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_price_rule_volumetric_weight/odoo/addons/delivery_price_rule_volumetric_weight
  setup/delivery_price_rule_volumetric_weight/setup.py
  stock_picking_delivery_link/__manifest__.py
Labels: 13.0.project_mi_465

#311 Back-merge from 13.0.project_MI_465 to 13.0.project_MI_465.test
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  base_delivery_carrier_label/tests/test_send.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/stock_picking.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
  delivery_price_rule_volumetric_weight/README.rst
  delivery_price_rule_volumetric_weight/__init__.py
  delivery_price_rule_volumetric_weight/__manifest__.py
  delivery_price_rule_volumetric_weight/i18n/delivery_price_rule_volumetric_weight.pot
  delivery_price_rule_volumetric_weight/i18n/es.po
  delivery_price_rule_volumetric_weight/models/__init__.py
  delivery_price_rule_volumetric_weight/models/delivery_carrier.py
  delivery_price_rule_volumetric_weight/models/delivery_price_rule.py
  delivery_price_rule_volumetric_weight/readme/CONFIGURE.rst
  delivery_price_rule_volumetric_weight/readme/CONTRIBUTORS.rst
  delivery_price_rule_volumetric_weight/readme/DESCRIPTION.rst
  delivery_price_rule_volumetric_weight/readme/USAGE.rst
  delivery_price_rule_volumetric_weight/static/description/icon.png
  delivery_price_rule_volumetric_weight/static/description/index.html
  delivery_price_rule_volumetric_weight/tests/__init__.py
  delivery_price_rule_volumetric_weight/tests/test_delivery_price.py
  delivery_send_to_shipper_at_operation/__manifest__.py
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_price_rule_volumetric_weight/odoo/addons/delivery_price_rule_volumetric_weight
  setup/delivery_price_rule_volumetric_weight/setup.py
  stock_picking_delivery_link/__manifest__.py
Labels: 13.0.project_mi_465.test
