Repository brain-tec/delivery-carrier, pull requests merged in 2021-05, with the labels that each got.

#251 Syncing from upstream OCA/delivery-carrier (10.0)
  README.md
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
  delivery_carrier_label_postlogistics/views/stock.xml
Labels: 10.0

#252 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_carrier_service_level/README.rst
  delivery_carrier_service_level/__init__.py
  delivery_carrier_service_level/__manifest__.py
  delivery_carrier_service_level/i18n/delivery_carrier_service_level.pot
  delivery_carrier_service_level/models/__init__.py
  delivery_carrier_service_level/models/carrier_service_level.py
  delivery_carrier_service_level/models/stock_picking.py
  delivery_carrier_service_level/readme/CONFIGURE.rst
  delivery_carrier_service_level/readme/CONTRIBUTORS.rst
  delivery_carrier_service_level/readme/DESCRIPTION.rst
  delivery_carrier_service_level/readme/USAGE.rst
  delivery_carrier_service_level/security/ir.model.access.csv
  delivery_carrier_service_level/static/description/icon.png
  delivery_carrier_service_level/static/description/index.html
  delivery_carrier_service_level/views/carrier_service_level.xml
  delivery_carrier_service_level/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_service_level/odoo/addons/delivery_carrier_service_level
  setup/delivery_carrier_service_level/setup.py
Labels: 13.0

#254 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_postlogistics/README.rst
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/product_packaging.py
  delivery_postlogistics/models/res_partner.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/models/stock_quant_package.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/readme/CONFIGURE.rst
  delivery_postlogistics/readme/INSTALL.rst
  delivery_postlogistics/static/description/index.html
  delivery_postlogistics/views/delivery.xml
  delivery_postlogistics/views/postlogistics_license.xml
  delivery_postlogistics/views/product_packaging.xml
Labels: 13.0

#256 [bt#14318] Added sudo to postlogistics retrieval of delivery carrier
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465.test

#255 [bt#14318] Added sudo to postlogistics retrieval of delivery carrier
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465

#257 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_package_fee/__manifest__.py
  delivery_package_fee/i18n/delivery_package_fee.pot
  delivery_package_fee/models/delivery_carrier.py
  delivery_package_fee/models/delivery_package_fee.py
  delivery_package_fee/models/sale_order_line.py
  delivery_package_fee/views/delivery_carrier_views.xml
Labels: 13.0

#258 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  partner_delivery_schedule/i18n/it.po
  partner_delivery_zone/i18n/it.po
Labels: 12.0

#261 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/stock_picking.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/readme/DESCRIPTION.rst
  delivery_state/readme/USAGE.rst
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/stock_picking_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_state/odoo/addons/delivery_state
  setup/delivery_state/setup.py
Labels: 14.0

#262 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0

#263 Syncing from upstream OCA/delivery-carrier (14.0)
  .copier-answers.yml
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  delivery_carrier_info/i18n/fr.po
Labels: 14.0

#264 Update 20210524 - delivery-carrier - OCA 13.0
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465

#265 Update 20210524 - delivery-carrier - OCA 13.0
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465.test

#266 Syncing from upstream OCA/delivery-carrier (12.0)
  base_delivery_carrier_label/tests/carrier_label_case.py
  delivery_carrier_label_paazl/__manifest__.py
  delivery_carrier_label_paazl/data/delivery_carrier.xml
  delivery_carrier_label_paazl/i18n/delivery_carrier_label_paazl.pot
  delivery_carrier_label_paazl/models/stock_picking.py
  delivery_carrier_label_paazl/tests/test_delivery_carrier_label_paazl.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: 12.0

#267 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_carrier_info/i18n/es.po
Labels: 13.0

#268 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: 13.0
