Repository brain-tec/delivery-carrier, pull requests merged in 2021-07, with the labels that each got.

#281 [bt#15025] Fixed Packstation handling when generating labels, added tracking to dhl
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465, bug, feature

#285 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_city/README.rst
  delivery_carrier_city/__init__.py
  delivery_carrier_city/__manifest__.py
  delivery_carrier_city/i18n/delivery_carrier_city.pot
  delivery_carrier_city/models/__init__.py
  delivery_carrier_city/models/delivery_carrier.py
  delivery_carrier_city/readme/CONTRIBUTORS.rst
  delivery_carrier_city/readme/DESCRIPTION.rst
  delivery_carrier_city/static/description/icon.png
  delivery_carrier_city/static/description/index.html
  delivery_carrier_city/tests/__init__.py
  delivery_carrier_city/tests/test_delivery_carrier_city.py
  delivery_carrier_city/views/delivery_carrier.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_city/odoo/addons/delivery_carrier_city
  setup/delivery_carrier_city/setup.py
  setup/stock_picking_delivery_link/odoo/addons/stock_picking_delivery_link
  setup/stock_picking_delivery_link/setup.py
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__init__.py
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/i18n/stock_picking_delivery_link.pot
  stock_picking_delivery_link/models/__init__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/readme/CONTRIBUTORS.rst
  stock_picking_delivery_link/readme/DESCRIPTION.rst
  stock_picking_delivery_link/static/description/icon.png
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/__init__.py
  stock_picking_delivery_link/tests/common.py
  stock_picking_delivery_link/tests/test_delivery_link.py
  stock_picking_delivery_link/views/stock_picking.xml
Labels: 14.0

#286 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: 12.0

#287 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_multi_destination/README.rst
  delivery_multi_destination/__init__.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/demo/delivery_carrier_demo.xml
  delivery_multi_destination/i18n/cs_CZ.po
  delivery_multi_destination/i18n/de.po
  delivery_multi_destination/i18n/delivery_multi_destination.pot
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/i18n/fr.po
  delivery_multi_destination/i18n/it.po
  delivery_multi_destination/i18n/nl.po
  delivery_multi_destination/i18n/nl_NL.po
  delivery_multi_destination/i18n/pt_BR.po
  delivery_multi_destination/i18n/sl.po
  delivery_multi_destination/i18n/zh_CN.po
  delivery_multi_destination/models/__init__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/readme/CONFIGURE.rst
  delivery_multi_destination/readme/CONTRIBUTORS.rst
  delivery_multi_destination/readme/DESCRIPTION.rst
  delivery_multi_destination/readme/ROADMAP.rst
  delivery_multi_destination/readme/USAGE.rst
  delivery_multi_destination/static/description/icon.png
  delivery_multi_destination/static/description/index.html
  delivery_multi_destination/tests/__init__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_multi_destination/odoo/addons/delivery_multi_destination
  setup/delivery_multi_destination/setup.py
Labels: 14.0

#288 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/i18n/delivery_roulier.pot
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/readme/CONTRIBUTORS.rst
  delivery_roulier/readme/DESCRIPTION.rst
  delivery_roulier/readme/USAGE.rst
  delivery_roulier/static/description/icon.png
  delivery_roulier/static/description/index.html
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  delivery_roulier/views/carrier_account.xml
  delivery_roulier/views/stock_quant_package.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_roulier/odoo/addons/delivery_roulier
  setup/delivery_roulier/setup.py
  test-requirements.txt
Labels: 14.0

#290 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_roulier_option/README.rst
  delivery_roulier_option/__init__.py
  delivery_roulier_option/__manifest__.py
  delivery_roulier_option/data/delivery.xml
  delivery_roulier_option/i18n/delivery_roulier_option.pot
  delivery_roulier_option/models/__init__.py
  delivery_roulier_option/models/delivery_option.py
  delivery_roulier_option/models/stock_picking.py
  delivery_roulier_option/models/stock_quant_package.py
  delivery_roulier_option/readme/CONTRIBUTORS.rst
  delivery_roulier_option/readme/DESCRIPTION.rst
  delivery_roulier_option/static/description/icon.png
  delivery_roulier_option/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_roulier_option/odoo/addons/delivery_roulier_option
  setup/delivery_roulier_option/setup.py
Labels: 14.0

#291 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/models/stock.py
Labels: 12.0

#292 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_roulier/tests/test_delivery_roulier.py
  delivery_roulier_laposte_fr/README.rst
  delivery_roulier_laposte_fr/__init__.py
  delivery_roulier_laposte_fr/__manifest__.py
  delivery_roulier_laposte_fr/data/delivery.xml
  delivery_roulier_laposte_fr/models/__init__.py
  delivery_roulier_laposte_fr/models/delivery.py
  delivery_roulier_laposte_fr/models/stock_picking.py
  delivery_roulier_laposte_fr/models/stock_quant_package.py
  delivery_roulier_laposte_fr/readme/CONFIGURE.rst
  delivery_roulier_laposte_fr/readme/CONTRIBUTORS.rst
  delivery_roulier_laposte_fr/readme/CREDITS.rst
  delivery_roulier_laposte_fr/readme/DESCRIPTION.rst
  delivery_roulier_laposte_fr/static/description/icon.png
  delivery_roulier_laposte_fr/static/description/index.html
  delivery_roulier_laposte_fr/static/description/laposte_small.png
  delivery_roulier_laposte_fr/static/description/logo.jpg
  delivery_roulier_laposte_fr/tests/__init__.py
  delivery_roulier_laposte_fr/tests/cassettes/LaposteLabelDomCase.test_labels.yaml
  delivery_roulier_laposte_fr/tests/cassettes/LaposteLabelFranceCase.test_labels.yaml
  delivery_roulier_laposte_fr/tests/test_laposte_label_dom.py
  delivery_roulier_laposte_fr/tests/test_laposte_label_france.py
  delivery_roulier_laposte_fr/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_roulier_laposte_fr/odoo/addons/delivery_roulier_laposte_fr
  setup/delivery_roulier_laposte_fr/setup.py
  test-requirements.txt
Labels: 14.0

#293 Syncing from upstream OCA/delivery-carrier (12.0)
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/views/delivery.xml
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/i18n/delivery_carrier_label_ups.pot
  delivery_carrier_label_ups/models/stock_picking.py
Labels: 12.0

#294 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_package_fee/__manifest__.py
  delivery_package_fee/models/sale_order.py
  delivery_package_fee/models/stock_picking.py
Labels: 13.0

#295 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/tests/test_sanitize_values.py
Labels: 13.0

#296 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/models/delivery.py
  delivery_carrier_label_postlogistics/tests/test_delivery.py
Labels: 12.0
