Repository brain-tec/delivery-carrier, pull requests merged in 2022-06, with the labels that each got.

#444 [bt#19442] Re: MSHOP orders from Amazon are currently not imported in…
  delivery_dhl_de/models/stock_picking.py
Labels: enhancement, 13.0.project_mi_465.test

#443 [bt#19442] Re: MSHOP orders from Amazon are currently not imported in…
  delivery_dhl_de/models/stock_picking.py
Labels: enhancement, 13.0.project_mi_465

#446 [bt#19438] Fix DHL Response Handling
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test

#445 [bt#19438] Fix DHL Response Handling
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465

#450 Bugfixing pre-commit errors
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/stock_picking.py
Labels: bug, 13.0.project_mi_465

#449 Updating from latest OCA 13.0
  README.md
  connector_routific/README.rst
  connector_routific/__init__.py
  connector_routific/__manifest__.py
  connector_routific/data/sequence.xml
  connector_routific/i18n/connector_routific.pot
  connector_routific/i18n/es.po
  connector_routific/models/__init__.py
  connector_routific/models/product_attribute.py
  connector_routific/models/res_partner.py
  connector_routific/models/routific_config.py
  connector_routific/models/routific_project.py
  connector_routific/models/routific_project_driver.py
  connector_routific/models/stock_picking.py
  connector_routific/readme/CONFIGURE.rst
  connector_routific/readme/CONTRIBUTORS.rst
  connector_routific/readme/DESCRIPTION.rst
  connector_routific/readme/USAGE.rst
  connector_routific/security/ir.model.access.csv
  connector_routific/static/description/icon.png
  connector_routific/static/description/index.html
  connector_routific/tests/__init__.py
  connector_routific/tests/test_connector_routific.py
  connector_routific/views/product_attribute_views.xml
  connector_routific/views/res_partner_view.xml
  connector_routific/views/routific_config_views.xml
  connector_routific/views/routific_driver_views.xml
  connector_routific/views/routific_project_driver_view.xml
  connector_routific/views/routific_project_views.xml
  connector_routific/views/stock_picking_views.xml
  connector_routific/wizards/__init__.py
  connector_routific/wizards/routific_project_creator.py
  connector_routific/wizards/routific_project_creator_view.xml
  delivery_auto_refresh/i18n/es.po
  delivery_carrier_pricelist/i18n/es.po
  delivery_carrier_pricelist/i18n/es_CL.po
  delivery_carrier_pricelist/i18n/es_VE.po
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_purchase/i18n/es.po
  partner_delivery_zone/i18n/es.po
  requeriments.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/connector_routific/odoo/addons/connector_routific
  setup/connector_routific/setup.py
Labels: 13.0.project_mi_465

#452 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_correos_express/__manifest__.py
  delivery_correos_express/models/delivery_carrier.py
Labels: 14.0

#453 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
Labels: 13.0

#454 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
Labels: 13.0

#455 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_tnt_oca/README.rst
  delivery_tnt_oca/__init__.py
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Pricing Integration Guide v3 Schema.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect Shipping Integration Guide v3.pdf
  delivery_tnt_oca/doc/ExpressConnect/ExpressConnect_Tracking_V3_1.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel Integration Guide v1.10.pdf
  delivery_tnt_oca/doc/ExpressLabel/ExpressLabel_Integration Guide_Arrangements.pdf
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/__init__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/product_packaging.py
  delivery_tnt_oca/models/stock_picking.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/readme/CONFIGURE.rst
  delivery_tnt_oca/readme/CONTRIBUTORS.rst
  delivery_tnt_oca/readme/DESCRIPTION.rst
  delivery_tnt_oca/readme/ROADMAP.rst
  delivery_tnt_oca/readme/USAGE.rst
  delivery_tnt_oca/report/picking_templates.xml
  delivery_tnt_oca/report/stock_report_views.xml
  delivery_tnt_oca/static/description/icon.png
  delivery_tnt_oca/static/description/index.html
  delivery_tnt_oca/tests/__init__.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_tnt_oca/odoo/addons/delivery_tnt_oca
  setup/delivery_tnt_oca/setup.py
Labels: 14.0

#456 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/models/tnt_request.py
Labels: 14.0

#457 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
Labels: 13.0.project_mi_465

#458 Backmerging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
Labels: 13.0.project_mi_465.test
