Repository brain-tec/delivery-carrier, pull requests merged in 2022-04, with the labels that each got.

#409 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/tests/test_send.py
  delivery_carrier_pricelist/__manifest__.py
  delivery_carrier_pricelist/tests/test_delivery_pricelist.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_package_fee/__manifest__.py
  delivery_package_fee/tests/test_package_fee.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/models/stock_picking.py
Labels: 14.0

#410 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__init__.py
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/__init__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/readme/CONTRIBUTORS.rst
  delivery_auto_refresh/readme/DESCRIPTION.rst
  delivery_auto_refresh/readme/ROADMAP.rst
  delivery_auto_refresh/static/description/icon.png
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/__init__.py
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
  delivery_auto_refresh/utils.py
  delivery_auto_refresh/views/sale_order_views.xml
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/models/product_packaging.py
  delivery_postlogistics/tests/__init__.py
  delivery_postlogistics/tests/test_packaging_code.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_auto_refresh/odoo/addons/delivery_auto_refresh
  setup/delivery_auto_refresh/setup.py
Labels: 14.0

#411 Syncing from upstream OCA/delivery-carrier (14.0)
  base_delivery_carrier_files/i18n/it.po
  delivery_auto_refresh/i18n/it.po
  partner_delivery_zone/i18n/it.po
Labels: 14.0

#415 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/views/delivery_carrier_view.xml
Labels: 13.0

#416 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  delivery_price_rule_untaxed/README.rst
  delivery_price_rule_untaxed/__init__.py
  delivery_price_rule_untaxed/__manifest__.py
  delivery_price_rule_untaxed/data/delivery_price_rule_untaxed_demo.xml
  delivery_price_rule_untaxed/i18n/delivery_price_rule_untaxed.pot
  delivery_price_rule_untaxed/i18n/fr.po
  delivery_price_rule_untaxed/i18n/it.po
  delivery_price_rule_untaxed/models/__init__.py
  delivery_price_rule_untaxed/models/delivery_carrier.py
  delivery_price_rule_untaxed/models/delivery_price_rule.py
  delivery_price_rule_untaxed/readme/CONTRIBUTORS.rst
  delivery_price_rule_untaxed/readme/DESCRIPTION.rst
  delivery_price_rule_untaxed/static/description/icon.png
  delivery_price_rule_untaxed/static/description/index.html
  delivery_price_rule_untaxed/tests/__init__.py
  delivery_price_rule_untaxed/tests/test_delivery_price_rule_untaxed.py
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_price_rule_untaxed/odoo/addons/delivery_price_rule_untaxed
  setup/delivery_price_rule_untaxed/setup.py
Labels: 14.0

#417 Syncing from upstream OCA/delivery-carrier (9.0)
  delivery_roulier_dpd/i18n/it.po
Labels: 9.0

#418 Syncing from upstream OCA/delivery-carrier (14.0)
  base_delivery_carrier_label/i18n/it.po
  delivery_price_rule_untaxed/i18n/it.po
Labels: 14.0

#419 Syncing from upstream OCA/delivery-carrier (13.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  delivery_multi_destination/i18n/es.po
Labels: 13.0

#420 Syncing from upstream OCA/delivery-carrier (14.0)
  delivery_multi_destination/i18n/es.po
Labels: 14.0

#422 Adding development status to fix checks
  delivery_package_number/__manifest__.py
Labels: 13.0.project_mi_465

#423 Adding development status to fix some checks
  delivery_price_method/__manifest__.py
Labels: 13.0.project_mi_465

#424 Adding development status to fix some tests
  delivery_state/__manifest__.py
Labels: 13.0.project_mi_465

#425 Missing setup files for modules delivery_dhl_de and delivery_services
  setup/delivery_dhl_de/odoo/addons/delivery_dhl_de
  setup/delivery_dhl_de/setup.py
  setup/delivery_services/odoo/addons/delivery_services
  setup/delivery_services/setup.py
Labels: 13.0.project_mi_465

#421 Updating from latest OCA 13.0
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/views/delivery_carrier_view.xml
Labels: 13.0.project_mi_465

#426 Back-merge from 13.0.project_MI_465 into 13.0.project_MI_465.test
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/i18n/es.po
  delivery_multi_destination/models/delivery_carrier.py
  delivery_multi_destination/views/delivery_carrier_view.xml
  delivery_package_number/__manifest__.py
  delivery_price_method/__manifest__.py
  delivery_state/__manifest__.py
  setup/delivery_dhl_de/odoo/addons/delivery_dhl_de
  setup/delivery_dhl_de/setup.py
  setup/delivery_services/odoo/addons/delivery_services
  setup/delivery_services/setup.py
Labels: 13.0.project_mi_465.test, back-merge

#427 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_package_number/README.rst
  delivery_package_number/__manifest__.py
  delivery_package_number/static/description/index.html
  delivery_price_method/README.rst
  delivery_price_method/__manifest__.py
  delivery_price_method/static/description/index.html
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/static/description/index.html
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
Labels: 13.0
