Repository brain-tec/delivery-carrier, pull requests merged in 2022-08, with the labels that each got.

#462 Syncing from upstream OCA/delivery-carrier (15.0)
  README.md
  partner_delivery_zone/README.rst
  partner_delivery_zone/__init__.py
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/i18n/de.po
  partner_delivery_zone/i18n/es.po
  partner_delivery_zone/i18n/fr_FR.po
  partner_delivery_zone/i18n/it.po
  partner_delivery_zone/i18n/partner_delivery_zone.pot
  partner_delivery_zone/i18n/zh_CN.po
  partner_delivery_zone/models/__init__.py
  partner_delivery_zone/models/partner_delivery_zone.py
  partner_delivery_zone/models/res_partner.py
  partner_delivery_zone/models/sale_order.py
  partner_delivery_zone/models/stock_move.py
  partner_delivery_zone/models/stock_picking.py
  partner_delivery_zone/readme/CONFIGURATION.rst
  partner_delivery_zone/readme/CONFIGURE.rst
  partner_delivery_zone/readme/CONTRIBUTORS.rst
  partner_delivery_zone/readme/DESCRIPTION.rst
  partner_delivery_zone/readme/ROADMAP.rst
  partner_delivery_zone/readme/USAGE.rst
  partner_delivery_zone/security/ir.model.access.csv
  partner_delivery_zone/static/description/icon.png
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/tests/__init__.py
  partner_delivery_zone/tests/test_partner_delivery_zone.py
  partner_delivery_zone/views/partner_delivery_zone_view.xml
  partner_delivery_zone/views/report_deliveryslip.xml
  partner_delivery_zone/views/report_shipping.xml
  partner_delivery_zone/views/res_partner_view.xml
  partner_delivery_zone/views/sale_order_view.xml
  partner_delivery_zone/views/stock_picking_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/partner_delivery_zone/odoo/addons/partner_delivery_zone
  setup/partner_delivery_zone/setup.py
Labels: 15.0

#463 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_send_to_shipper_at_operation/__manifest__.py
  delivery_send_to_shipper_at_operation/models/stock_picking.py
  delivery_send_to_shipper_at_operation/tests/test_send_to_shipper.py
Labels: 14.0

#464 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/__init__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/stock_picking.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/views/stock_picking_view.xml
Labels: 13.0

#465 Syncing from upstream OCA/delivery-carrier (15.0)
  README.md
  delivery_package_number/README.rst
  delivery_package_number/__init__.py
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/models/__init__.py
  delivery_package_number/models/stock_picking.py
  delivery_package_number/readme/CONTRIBUTORS.rst
  delivery_package_number/readme/DESCRIPTION.rst
  delivery_package_number/readme/USAGE.rst
  delivery_package_number/static/description/icon.png
  delivery_package_number/static/description/index.html
  delivery_package_number/tests/__init__.py
  delivery_package_number/tests/test_delivery_package_number.py
  delivery_package_number/views/stock_picking_views.xml
  delivery_package_number/wizard/__init__.py
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
  delivery_translatable/README.rst
  delivery_translatable/__init__.py
  delivery_translatable/__manifest__.py
  delivery_translatable/i18n/delivery_translatable.pot
  delivery_translatable/models/__init__.py
  delivery_translatable/models/delivery.py
  delivery_translatable/readme/CONTRIBUTORS.rst
  delivery_translatable/readme/DESCRIPTION.rst
  delivery_translatable/static/description/icon.png
  delivery_translatable/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_package_number/odoo/addons/delivery_package_number
  setup/delivery_package_number/setup.py
  setup/delivery_translatable/odoo/addons/delivery_translatable
  setup/delivery_translatable/setup.py
Labels: 15.0

#466 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_price_method/README.rst
  delivery_price_method/__init__.py
  delivery_price_method/__manifest__.py
  delivery_price_method/i18n/delivery_price_method.pot
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_price_method/models/__init__.py
  delivery_price_method/models/delivery_carrier.py
  delivery_price_method/readme/CONTRIBUTORS.rst
  delivery_price_method/readme/DESCRIPTION.rst
  delivery_price_method/readme/USAGE.rst
  delivery_price_method/static/description/icon.png
  delivery_price_method/static/description/index.html
  delivery_price_method/tests/__init__.py
  delivery_price_method/tests/test_delivery_price_method.py
  delivery_price_method/views/delivery_carrier_views.xml
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_price_method/odoo/addons/delivery_price_method
  setup/delivery_price_method/setup.py
Labels: 14.0

#467 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/__init__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/stock_picking.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/views/stock_picking_view.xml
Labels: 13.0.project_mi_465

#469 Backmerging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_tnt_oca/__manifest__.py
  delivery_tnt_oca/data/product_packaging_data.xml
  delivery_tnt_oca/i18n/delivery_tnt_oca.pot
  delivery_tnt_oca/i18n/es.po
  delivery_tnt_oca/models/delivery_carrier.py
  delivery_tnt_oca/models/tnt_request.py
  delivery_tnt_oca/tests/test_delivery_tnt.py
  delivery_tnt_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/__manifest__.py
  delivery_ups_oca/i18n/delivery_ups_oca.pot
  delivery_ups_oca/models/__init__.py
  delivery_ups_oca/models/delivery_carrier.py
  delivery_ups_oca/models/stock_picking.py
  delivery_ups_oca/models/ups_request.py
  delivery_ups_oca/tests/test_delivery_ups.py
  delivery_ups_oca/views/delivery_carrier_view.xml
  delivery_ups_oca/views/stock_picking_view.xml
Labels: 13.0.project_mi_465.test

#470 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 13.0

#471 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 14.0

#472 Syncing from upstream OCA/delivery-carrier (15.0)
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 15.0

#473 [FIX] pre-commit run
  requirements.txt
  setup/delivery_dhl_de/odoo/addons/delivery_dhl_de
  setup/delivery_dhl_de/setup.py
Labels: 15.0.project_mi_465.t130466

#459 [t130466][mt13433] MIDE DEV V15 - DHL (Includes Migration)
  delivery_dhl_de/README.rst
  delivery_dhl_de/__init__.py
  delivery_dhl_de/__manifest__.py
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1-schema-bcs_base.xsd
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1-schema-cis_base.xsd
  delivery_dhl_de/dhl_de_api/geschaeftskundenversand-api-3.1.wsdl
  delivery_dhl_de/models/__init__.py
  delivery_dhl_de/models/delivery_carrier.py
  delivery_dhl_de/models/dhl_request.py
  delivery_dhl_de/models/res_partner.py
  delivery_dhl_de/models/sale_order.py
  delivery_dhl_de/models/stock_package_type.py
  delivery_dhl_de/models/stock_picking.py
  delivery_dhl_de/views/delivery_carrier.xml
  delivery_dhl_de/views/sale_order_views.xml
  delivery_dhl_de/views/stock_picking_views.xml
  delivery_dhl_de/views/view_res_partner.xml
  requirements.txt
  setup/delivery_dhl_de/odoo/addons/delivery_dhl_de
  setup/delivery_dhl_de/setup.py
Labels: odoo_migration, 15.0.project_mi_465

#474 Syncing from upstream OCA/delivery-carrier (14.0)
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: 14.0

#475 Backmerging 15.0 into 15.0.project_MI_465
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 15.0.project_mi_465

#476 Backmerging 13.0 into 13.0.project_MI_465
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 13.0.project_mi_465

#477 Backmerging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_package_number/__manifest__.py
  delivery_package_number/i18n/delivery_package_number.pot
  delivery_package_number/i18n/es.po
  delivery_package_number/i18n/sl.po
  delivery_package_number/wizard/stock_immediate_transfer_views.xml
  delivery_package_number/wizard/stock_inmediate_transfer.py
Labels: 13.0.project_mi_465.test
