Repository brain-tec/delivery-carrier, pull requests merged in 2022-05, with the labels that each got.

#431 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/delivery_carrier.py
Labels: 14.0

#434 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  partner_delivery_zone/i18n/fr.po
Labels: 12.0

#435 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/models/sale_order.py
Labels: 13.0

#436 Merging 13.0 into 13.0.project_MI_465
  README.md
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/models/sale_order.py
Labels: 13.0.project_mi_465

#437 Merging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_free_fee_removal/__manifest__.py
  delivery_free_fee_removal/models/sale_order.py
Labels: 13.0.project_mi_465.test

#438 Syncing from upstream OCA/delivery-carrier (13.0)
  delivery_auto_refresh/i18n/es.po
  delivery_carrier_pricelist/i18n/es.po
  delivery_carrier_pricelist/i18n/es_CL.po
  delivery_carrier_pricelist/i18n/es_VE.po
  delivery_price_method/i18n/es.po
  delivery_price_method/i18n/es_CL.po
  delivery_price_method/i18n/es_VE.po
  delivery_purchase/i18n/es.po
  partner_delivery_zone/i18n/es.po
Labels: 13.0

#439 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_paazl/__manifest__.py
  delivery_carrier_label_paazl/data/delivery_carrier.xml
Labels: 12.0

#430 [bt#19090] Re: Fehlender Datenimport Odoo
  delivery_dhl_de/models/delivery_carrier.py
Labels: enhancement, 13.0.project_mi_465

#440 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/views/stock.xml
Labels: 14.0

#442 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  connector_routific/README.rst
  connector_routific/__init__.py
  connector_routific/__manifest__.py
  connector_routific/data/sequence.xml
  connector_routific/i18n/connector_routific.pot
  connector_routific/i18n/es.po
  connector_routific/models/__init__.py
  connector_routific/models/product_attribute.py
  connector_routific/models/res_partner.py
  connector_routific/models/routific_config.py
  connector_routific/models/routific_project.py
  connector_routific/models/routific_project_driver.py
  connector_routific/models/stock_picking.py
  connector_routific/readme/CONFIGURE.rst
  connector_routific/readme/CONTRIBUTORS.rst
  connector_routific/readme/DESCRIPTION.rst
  connector_routific/readme/USAGE.rst
  connector_routific/security/ir.model.access.csv
  connector_routific/static/description/icon.png
  connector_routific/static/description/index.html
  connector_routific/tests/__init__.py
  connector_routific/tests/test_connector_routific.py
  connector_routific/views/product_attribute_views.xml
  connector_routific/views/res_partner_view.xml
  connector_routific/views/routific_config_views.xml
  connector_routific/views/routific_driver_views.xml
  connector_routific/views/routific_project_driver_view.xml
  connector_routific/views/routific_project_views.xml
  connector_routific/views/stock_picking_views.xml
  connector_routific/wizards/__init__.py
  connector_routific/wizards/routific_project_creator.py
  connector_routific/wizards/routific_project_creator_view.xml
  requeriments.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/connector_routific/odoo/addons/connector_routific
  setup/connector_routific/setup.py
Labels: 13.0
