Repository brain-tec/delivery-carrier, pull requests merged in 2022-02, with the labels that each got.

#380 Syncing from upstream OCA/delivery-carrier (14.0)
  delivery_multi_destination/i18n/pt_BR.po
Labels: 14.0

#381 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_roulier/__manifest__.py
  delivery_roulier/models/stock_picking.py
Labels: 14.0

#382 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_price_method/__manifest__.py
  delivery_price_method/models/delivery_carrier.py
Labels: 13.0

#383 Syncing from upstream OCA/delivery-carrier (10.0)
  README.md
  delivery_carrier_label_postlogistics/__manifest__.py
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_postlogistics/postlogistics/web_service.py
Labels: 10.0

#384 Syncing from upstream OCA/delivery-carrier (12.0)
  delivery_carrier_label_postlogistics/i18n/am.po
  delivery_carrier_label_postlogistics/i18n/ar.po
  delivery_carrier_label_postlogistics/i18n/ca.po
  delivery_carrier_label_postlogistics/i18n/cs.po
  delivery_carrier_label_postlogistics/i18n/de.po
  delivery_carrier_label_postlogistics/i18n/delivery_carrier_label_postlogistics.pot
  delivery_carrier_label_postlogistics/i18n/el_GR.po
  delivery_carrier_label_postlogistics/i18n/es.po
  delivery_carrier_label_postlogistics/i18n/es_CR.po
  delivery_carrier_label_postlogistics/i18n/es_EC.po
  delivery_carrier_label_postlogistics/i18n/es_ES.po
  delivery_carrier_label_postlogistics/i18n/es_MX.po
  delivery_carrier_label_postlogistics/i18n/es_VE.po
  delivery_carrier_label_postlogistics/i18n/et.po
  delivery_carrier_label_postlogistics/i18n/fi.po
  delivery_carrier_label_postlogistics/i18n/fr.po
  delivery_carrier_label_postlogistics/i18n/gl.po
  delivery_carrier_label_postlogistics/i18n/hr_HR.po
  delivery_carrier_label_postlogistics/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/lt.po
  delivery_carrier_label_postlogistics/i18n/nl.po
  delivery_carrier_label_postlogistics/i18n/nl_BE.po
  delivery_carrier_label_postlogistics/i18n/pl.po
  delivery_carrier_label_postlogistics/i18n/pt.po
  delivery_carrier_label_postlogistics/i18n/pt_BR.po
  delivery_carrier_label_postlogistics/i18n/pt_PT.po
  delivery_carrier_label_postlogistics/i18n/ro.po
  delivery_carrier_label_postlogistics/i18n/ru.po
  delivery_carrier_label_postlogistics/i18n/sl.po
  delivery_carrier_label_postlogistics/i18n/th.po
  delivery_carrier_label_postlogistics/i18n/tr.po
  delivery_carrier_label_postlogistics/i18n/vi.po
  delivery_carrier_label_ups/__manifest__.py
  delivery_carrier_label_ups/i18n/delivery_carrier_label_ups.pot
  delivery_carrier_label_ups/models/stock_picking.py
  delivery_carrier_label_ups/tests/test_delivery_carrier_label_ups.py
Labels: 12.0

#385 Merging 13.0 into 13.0.project_MI_465
  README.md
  delivery_price_method/__manifest__.py
  delivery_price_method/models/delivery_carrier.py
Labels: 13.0.project_mi_465

#386 Merging 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_price_method/__manifest__.py
  delivery_price_method/models/delivery_carrier.py
Labels: 13.0.project_mi_465.test

#388 [t127621] Show delivery number in PostLogistics and DHL labels
  delivery_dhl_de/models/dhl_request.py
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465.test

#389 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: 13.0
