Repository brain-tec/delivery-carrier, pull requests merged in 2022-03, with the labels that each got.

#390 Updating from latest OCA 13.0
  README.md
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: 13.0.project_mi_465

#391 Back-merge from 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_auto_refresh/README.rst
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/data/ir_config_parameter.xml
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/models/stock_picking.py
  delivery_auto_refresh/readme/CONFIGURE.rst
  delivery_auto_refresh/static/description/index.html
  delivery_auto_refresh/tests/test_delivery_auto_refresh.py
Labels: 13.0.project_mi_465.test, back-merge

#387 [t127621] Show delivery number in PostLogistics and DHL labels
  delivery_dhl_de/models/dhl_request.py
  delivery_postlogistics/postlogistics/web_service.py
Labels: 13.0.project_mi_465

#396 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0

#397 Updating from latest OCA 13.0
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465

#398 Back-merge from 13.0.project_MI_465 into 13.0.project_MI_465.test
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
Labels: 13.0.project_mi_465.test, back-merge

#399 [t127902] Updated to add services on write of stock.picking
  delivery_services/models/stock_picking.py
Labels: 13.0.project_mi_465.test

#400 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/security/carrier_security.xml
  carrier_account_environment/README.rst
  carrier_account_environment/__init__.py
  carrier_account_environment/__manifest__.py
  carrier_account_environment/i18n/carrier_account_environment.pot
  carrier_account_environment/i18n/carrier_environment.pot
  carrier_account_environment/models/__init__.py
  carrier_account_environment/models/carrier_account.py
  carrier_account_environment/readme/CONFIGURE.rst
  carrier_account_environment/readme/CONTRIBUTORS.rst
  carrier_account_environment/readme/DESCRIPTION.rst
  carrier_account_environment/readme/USAGE.rst
  carrier_account_environment/static/description/icon.png
  carrier_account_environment/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/carrier_account_environment/odoo/addons/carrier_account_environment
  setup/carrier_account_environment/setup.py
Labels: 14.0

#401 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_carrier_label_batch/README.rst
  delivery_carrier_label_batch/__init__.py
  delivery_carrier_label_batch/__manifest__.py
  delivery_carrier_label_batch/data/ir.config_parameter.xml
  delivery_carrier_label_batch/i18n/de.po
  delivery_carrier_label_batch/i18n/delivery_carrier_label_batch.pot
  delivery_carrier_label_batch/i18n/fr.po
  delivery_carrier_label_batch/models/__init__.py
  delivery_carrier_label_batch/models/stock_batch_picking.py
  delivery_carrier_label_batch/pdf_utils.py
  delivery_carrier_label_batch/readme/CONFIGURE.rst
  delivery_carrier_label_batch/readme/CONTRIBUTORS.rst
  delivery_carrier_label_batch/readme/CREDITS.rst
  delivery_carrier_label_batch/readme/DESCRIPTION.rst
  delivery_carrier_label_batch/readme/USAGE.rst
  delivery_carrier_label_batch/security/ir.model.access.csv
  delivery_carrier_label_batch/static/description/icon.png
  delivery_carrier_label_batch/static/description/index.html
  delivery_carrier_label_batch/tests/__init__.py
  delivery_carrier_label_batch/tests/dummy.pdf
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_carrier_label_batch/views/stock_batch_picking.xml
  delivery_carrier_label_batch/wizard/__init__.py
  delivery_carrier_label_batch/wizard/apply_carrier.py
  delivery_carrier_label_batch/wizard/apply_carrier_view.xml
  delivery_carrier_label_batch/wizard/generate_labels.py
  delivery_carrier_label_batch/wizard/generate_labels_view.xml
  delivery_carrier_label_batch/zpl_utils.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_carrier_label_batch/odoo/addons/delivery_carrier_label_batch
  setup/delivery_carrier_label_batch/setup.py
Labels: 14.0

#402 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/i18n/ca.po
  delivery_auto_refresh/i18n/cs_CZ.po
  delivery_auto_refresh/i18n/de.po
  delivery_auto_refresh/i18n/delivery_auto_refresh.pot
  delivery_auto_refresh/i18n/el_GR.po
  delivery_auto_refresh/i18n/es.po
  delivery_auto_refresh/i18n/es_ES.po
  delivery_auto_refresh/i18n/es_VE.po
  delivery_auto_refresh/i18n/fi.po
  delivery_auto_refresh/i18n/fr.po
  delivery_auto_refresh/i18n/gl.po
  delivery_auto_refresh/i18n/hr.po
  delivery_auto_refresh/i18n/hr_HR.po
  delivery_auto_refresh/i18n/hu.po
  delivery_auto_refresh/i18n/it.po
  delivery_auto_refresh/i18n/nl.po
  delivery_auto_refresh/i18n/nl_NL.po
  delivery_auto_refresh/i18n/pt.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_auto_refresh/i18n/ro.po
  delivery_auto_refresh/i18n/sl.po
  delivery_auto_refresh/i18n/tr.po
  delivery_auto_refresh/i18n/tr_TR.po
  delivery_auto_refresh/i18n/vi_VN.po
  delivery_auto_refresh/i18n/zh_CN.po
  delivery_auto_refresh/models/sale_order.py
  delivery_auto_refresh/views/sale_order_views.xml
Labels: 13.0

#404 [t127902] Changed how we use the services so they work correctly. Added
  delivery_dhl_de/models/dhl_request.py
  delivery_services/models/shipment_service.py
  delivery_services/views/shipment_service.xml
Labels: feature, 13.0.project_mi_465.test

#405 [t127902] Added sudo to ir module module search
  delivery_dhl_de/models/dhl_request.py
Labels: 13.0.project_mi_465.test

#406 Syncing from upstream OCA/delivery-carrier (13.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: 13.0

#407 Syncing from upstream OCA/delivery-carrier (14.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  base_delivery_carrier_files/tests/test_base_delivery_carrier_files.py
  base_delivery_carrier_label/models/carrier_account.py
  base_delivery_carrier_label/models/delivery_carrier.py
  base_delivery_carrier_label/models/delivery_carrier_template_option.py
  base_delivery_carrier_label/models/shipping_label.py
  base_delivery_carrier_label/models/stock_picking.py
  base_delivery_carrier_label/models/stock_quant_package.py
  delivery_carrier_label_batch/models/stock_batch_picking.py
  delivery_carrier_label_batch/tests/test_generate_labels.py
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_roulier/models/stock_picking.py
Labels: 14.0

#408 Syncing from upstream OCA/delivery-carrier (15.0)
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
Labels: 15.0
