Repository brain-tec/delivery-carrier, pull requests merged in 2022-01, with the labels that each got.

#376 Syncing from upstream OCA/delivery-carrier (13.0)
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: 13.0

#377 Syncing from upstream OCA/delivery-carrier (14.0)
  base_delivery_carrier_label/i18n/fr.po
Labels: 14.0

#378 Updating from latest OCA 13.0
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: 13.0.project_mi_465

#379 Updating from latest 13.0.project_MI_465
  README.md
  delivery_auto_refresh/__manifest__.py
  delivery_auto_refresh/models/sale_order.py
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/tests/test_delivery_multi_destination.py
Labels: 13.0.project_mi_465.test
