Repository brain-tec/delivery-carrier, pull requests merged in 2023-06, with the labels that each got.

#604 Syncing from upstream OCA/delivery-carrier (8.0)
  base_delivery_carrier_files/i18n/it.po
  base_delivery_carrier_label/i18n/it.po
  delivery_carrier_deposit/i18n/it.po
  delivery_carrier_label_gls/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/it.po
Labels: 8.0

#605 Syncing from upstream OCA/delivery-carrier (9.0)
  base_delivery_carrier_label/i18n/it.po
  delivery_carrier_deposit/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/it.po
  sale_delivery_rate/i18n/it.po
  stock_picking_delivery_rate/i18n/it.po
Labels: 9.0

#606 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  delivery_automatic_package/README.rst
  delivery_automatic_package/__init__.py
  delivery_automatic_package/__manifest__.py
  delivery_automatic_package/i18n/delivery_automatic_package.pot
  delivery_automatic_package/models/__init__.py
  delivery_automatic_package/models/delivery_carrier.py
  delivery_automatic_package/models/res_company.py
  delivery_automatic_package/models/res_config_settings.py
  delivery_automatic_package/models/stock_picking.py
  delivery_automatic_package/readme/CONFIGURE.rst
  delivery_automatic_package/readme/CONTRIBUTORS.rst
  delivery_automatic_package/readme/DESCRIPTION.rst
  delivery_automatic_package/static/description/icon.png
  delivery_automatic_package/static/description/index.html
  delivery_automatic_package/tests/__init__.py
  delivery_automatic_package/tests/test_automatic_package.py
  delivery_automatic_package/views/delivery_carrier.xml
  delivery_automatic_package/views/res_config_settings.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_automatic_package/odoo/addons/delivery_automatic_package
  setup/delivery_automatic_package/setup.py
Labels: 16.0

#607 Syncing from upstream OCA/delivery-carrier (15.0)
  README.md
  delivery_multi_destination/__manifest__.py
  delivery_multi_destination/models/delivery_carrier.py
Labels: 15.0

#608 Syncing from upstream OCA/delivery-carrier (8.0)
  base_delivery_carrier_files/i18n/it.po
  base_delivery_carrier_label/i18n/it.po
  delivery_carrier_deposit/i18n/it.po
  delivery_carrier_label_postlogistics/i18n/it.po
Labels: 8.0

#609 Syncing from upstream OCA/delivery-carrier (10.0)
  base_delivery_carrier_files/i18n/it.po
Labels: 10.0

#611 Syncing from upstream OCA/delivery-carrier (9.0)
  delivery_carrier_deposit/i18n/it.po
Labels: 9.0

#612 Syncing from upstream OCA/delivery-carrier (9.0)
  delivery_carrier_deposit/i18n/it.po
Labels: 9.0

#613 Syncing from upstream OCA/delivery-carrier (12.0)
  partner_delivery_schedule/i18n/it.po
Labels: 12.0

#614 Syncing from upstream OCA/delivery-carrier (8.0)
  base_delivery_carrier_label/i18n/it.po
Labels: 8.0

#615 Syncing from upstream OCA/delivery-carrier (9.0)
  base_delivery_carrier_label/i18n/it.po
Labels: 9.0

#616 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_schenker/__manifest__.py
  delivery_schenker/i18n/delivery_schenker.pot
  delivery_schenker/i18n/es.po
  delivery_schenker/models/delivery_carrier.py
  delivery_schenker/tests/__init__.py
  delivery_schenker/tests/test_delivery_schenker.py
Labels: 14.0

#617 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  delivery_postlogistics_server_env/README.rst
  delivery_postlogistics_server_env/__init__.py
  delivery_postlogistics_server_env/__manifest__.py
  delivery_postlogistics_server_env/i18n/delivery_postlogistics_server_env.pot
  delivery_postlogistics_server_env/models/__init__.py
  delivery_postlogistics_server_env/models/delivery_carrier.py
  delivery_postlogistics_server_env/readme/CONTRIBUTORS.rst
  delivery_postlogistics_server_env/readme/CREDITS.rst
  delivery_postlogistics_server_env/readme/DESCRIPTION.rst
  delivery_postlogistics_server_env/static/description/icon.png
  delivery_postlogistics_server_env/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_postlogistics_server_env/odoo/addons/delivery_postlogistics_server_env
  setup/delivery_postlogistics_server_env/setup.py
Labels: 16.0

#618 [t136872] [ADD] add freeText attribute to web_service
  delivery_postlogistics/postlogistics/web_service.py
Labels: 15.0.project_mi_465
