Repository brain-tec/delivery-carrier, pull requests merged in 2024-07, with the labels that each got.

#790 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  delivery_dropoff_site/README.rst
  delivery_dropoff_site/__init__.py
  delivery_dropoff_site/__manifest__.py
  delivery_dropoff_site/demo/delivery_carrier.xml
  delivery_dropoff_site/demo/dropoff_site.xml
  delivery_dropoff_site/demo/res_groups.xml
  delivery_dropoff_site/demo/resource_calendar.xml
  delivery_dropoff_site/i18n/delivery_dropoff_site.pot
  delivery_dropoff_site/i18n/fr.po
  delivery_dropoff_site/migrations/16.0.1.0.0/pre-migrate.py
  delivery_dropoff_site/models/__init__.py
  delivery_dropoff_site/models/delivery_carrier.py
  delivery_dropoff_site/models/dropoff_site.py
  delivery_dropoff_site/models/res_partner.py
  delivery_dropoff_site/models/sale_order.py
  delivery_dropoff_site/models/stock_move.py
  delivery_dropoff_site/models/stock_picking.py
  delivery_dropoff_site/models/stock_rule.py
  delivery_dropoff_site/readme/CONFIGURE.rst
  delivery_dropoff_site/readme/CONTRIBUTORS.rst
  delivery_dropoff_site/readme/CREDITS.rst
  delivery_dropoff_site/readme/DESCRIPTION.rst
  delivery_dropoff_site/readme/USAGE.rst
  delivery_dropoff_site/security/ir.model.access.csv
  delivery_dropoff_site/static/description/dropoff_site_form.png
  delivery_dropoff_site/static/description/dropoff_site_form_calendar.png
  delivery_dropoff_site/static/description/dropoff_site_tree.png
  delivery_dropoff_site/static/description/icon.png
  delivery_dropoff_site/static/description/index.html
  delivery_dropoff_site/static/description/sale_order_form.png
  delivery_dropoff_site/views/view_delivery_carrier.xml
  delivery_dropoff_site/views/view_dropoff_site.xml
  delivery_dropoff_site/views/view_sale_order.xml
  delivery_dropoff_site/views/view_stock_picking.xml
  delivery_package_number/i18n/it.po
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/i18n/es.po
  delivery_postlogistics/i18n/it.po
  partner_delivery_schedule/i18n/es.po
  partner_delivery_schedule/i18n/it.po
  partner_delivery_schedule/i18n/nl.po
  partner_delivery_schedule/i18n/partner_delivery_schedule.pot
  partner_delivery_schedule/i18n/zh_CN.po
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_dropoff_site/odoo/addons/delivery_dropoff_site
  setup/delivery_dropoff_site/setup.py
Labels: 16.0

#791 Syncing from upstream OCA/delivery-carrier (17.0)
  base_delivery_carrier_label/i18n/it.po
Labels: 17.0

#792 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/models/stock_picking.py
  delivery_state/static/description/index.html
  delivery_state/views/stock_picking_views.xml
Labels: 14.0

#793 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  stock_picking_delivery_link/README.rst
  stock_picking_delivery_link/__manifest__.py
  stock_picking_delivery_link/models/stock_picking.py
  stock_picking_delivery_link/static/description/index.html
  stock_picking_delivery_link/tests/test_delivery_link.py
Labels: 16.0

#794 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_state/README.rst
  delivery_state/__manifest__.py
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/models/delivery_carrier.py
  delivery_state/readme/CONFIGURE.rst
  delivery_state/readme/CONTRIBUTORS.rst
  delivery_state/static/description/index.html
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/delivery_carrier_views.xml
Labels: 14.0

#795 Syncing from upstream OCA/delivery-carrier (16.0)
  carrier_account_environment/i18n/pt_BR.po
  delivery_auto_refresh/i18n/pt_BR.po
  delivery_postlogistics_server_env/i18n/pt_BR.po
Labels: 16.0

#796 Syncing from upstream OCA/delivery-carrier (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
Labels: 17.0

#797 Syncing from upstream OCA/delivery-carrier (16.0)
  delivery_dropoff_site/i18n/fr.po
Labels: 16.0

#798 [17.0][MIG] delivery_postlogistics: Migration to 17.0
  delivery_postlogistics/README.rst
  delivery_postlogistics/__init__.py
  delivery_postlogistics/__manifest__.py
  delivery_postlogistics/data/barcode handbuch.PDF
  delivery_postlogistics/data/delivery.xml
  delivery_postlogistics/data/partner.xml
  delivery_postlogistics/data/product.xml
  delivery_postlogistics/i18n/delivery_postlogistics.pot
  delivery_postlogistics/i18n/es.po
  delivery_postlogistics/i18n/it.po
  delivery_postlogistics/models/__init__.py
  delivery_postlogistics/models/delivery_carrier.py
  delivery_postlogistics/models/postlogistics_carrier_template_options.py
  delivery_postlogistics/models/postlogistics_license.py
  delivery_postlogistics/models/postlogistics_shipping_label.py
  delivery_postlogistics/models/res_partner.py
  delivery_postlogistics/models/stock_move.py
  delivery_postlogistics/models/stock_package_type.py
  delivery_postlogistics/models/stock_picking.py
  delivery_postlogistics/models/stock_quant_package.py
  delivery_postlogistics/postlogistics/__init__.py
  delivery_postlogistics/postlogistics/web_service.py
  delivery_postlogistics/pyproject.toml
  delivery_postlogistics/readme/CONFIGURE.md
  delivery_postlogistics/readme/CONTRIBUTORS.md
  delivery_postlogistics/readme/CREDITS.md
  delivery_postlogistics/readme/DESCRIPTION.md
  delivery_postlogistics/readme/ROADMAP.md
  delivery_postlogistics/security/ir.model.access.csv
  delivery_postlogistics/static/description/icon.svg
  delivery_postlogistics/static/description/index.html
  delivery_postlogistics/static/img/postlogistics-logo.jpg
  delivery_postlogistics/tests/__init__.py
  delivery_postlogistics/tests/common.py
  delivery_postlogistics/tests/fixtures/cassettes/test_missing_language.yaml
  delivery_postlogistics/tests/fixtures/cassettes/test_store_label.yaml
  delivery_postlogistics/tests/test_packaging_code.py
  delivery_postlogistics/tests/test_postlogistics.py
  delivery_postlogistics/tests/test_sanitize_values.py
  delivery_postlogistics/views/delivery.xml
  delivery_postlogistics/views/postlogistics_license.xml
  delivery_postlogistics/views/res_partner_view.xml
  delivery_postlogistics/views/stock.xml
  delivery_postlogistics/views/stock_package_type_view.xml
  delivery_postlogistics/views/stock_quant_package_view.xml
  test-requirements.txt
Labels: 17.0.project_TH_736

#799 Syncing from upstream OCA/delivery-carrier (16.0)
  delivery_dropoff_site/i18n/it.po
Labels: 16.0

#800 Syncing from upstream OCA/delivery-carrier (14.0)
  README.md
  delivery_purchase/README.rst
  delivery_purchase/__manifest__.py
  delivery_purchase/models/delivery_carrier.py
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/readme/CONTRIBUTORS.rst
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_roulier/README.rst
  delivery_roulier/__manifest__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/static/description/index.html
Labels: 14.0

#801 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  delivery_roulier_option/README.rst
  delivery_roulier_option/__init__.py
  delivery_roulier_option/__manifest__.py
  delivery_roulier_option/data/delivery.xml
  delivery_roulier_option/i18n/delivery_roulier_option.pot
  delivery_roulier_option/i18n/es.po
  delivery_roulier_option/models/__init__.py
  delivery_roulier_option/models/delivery_option.py
  delivery_roulier_option/models/stock_picking.py
  delivery_roulier_option/models/stock_quant_package.py
  delivery_roulier_option/readme/CONTRIBUTORS.rst
  delivery_roulier_option/readme/DESCRIPTION.rst
  delivery_roulier_option/static/description/icon.png
  delivery_roulier_option/static/description/index.html
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_roulier_option/odoo/addons/delivery_roulier_option
  setup/delivery_roulier_option/setup.py
Labels: 16.0

#802 Syncing from upstream OCA/delivery-carrier (17.0)
  README.md
  base_delivery_carrier_label/README.rst
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/models/stock_quant_package.py
  base_delivery_carrier_label/static/description/index.html
  base_delivery_carrier_label/tests/test_get_weight.py
Labels: 17.0

#803 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  partner_delivery_schedule/README.rst
  partner_delivery_schedule/__manifest__.py
  partner_delivery_schedule/static/description/index.html
  partner_delivery_schedule/views/report_shipping.xml
  partner_delivery_zone/README.rst
  partner_delivery_zone/__manifest__.py
  partner_delivery_zone/static/description/index.html
  partner_delivery_zone/views/report_deliveryslip.xml
  stock_picking_report_delivery_cost/README.rst
  stock_picking_report_delivery_cost/__manifest__.py
  stock_picking_report_delivery_cost/i18n/es.po
  stock_picking_report_delivery_cost/i18n/fr.po
  stock_picking_report_delivery_cost/i18n/it.po
  stock_picking_report_delivery_cost/i18n/stock_picking_report_delivery_cost.pot
  stock_picking_report_delivery_cost/report/report_deliveryslip.xml
  stock_picking_report_delivery_cost/static/description/index.html
Labels: 16.0

#804 Syncing from upstream OCA/delivery-carrier (17.0)
  README.md
  delivery_roulier/README.rst
  delivery_roulier/__init__.py
  delivery_roulier/__manifest__.py
  delivery_roulier/decorator.py
  delivery_roulier/demo/product.xml
  delivery_roulier/i18n/delivery_roulier.pot
  delivery_roulier/i18n/es.po
  delivery_roulier/i18n/it.po
  delivery_roulier/models/__init__.py
  delivery_roulier/models/delivery_carrier.py
  delivery_roulier/models/stock_move_line.py
  delivery_roulier/models/stock_picking.py
  delivery_roulier/models/stock_quant_package.py
  delivery_roulier/pyproject.toml
  delivery_roulier/readme/CONFIGURE.md
  delivery_roulier/readme/CONTRIBUTORS.md
  delivery_roulier/readme/DESCRIPTION.md
  delivery_roulier/readme/USAGE.md
  delivery_roulier/static/description/icon.png
  delivery_roulier/static/description/index.html
  delivery_roulier/tests/__init__.py
  delivery_roulier/tests/models.py
  delivery_roulier/tests/test_delivery_roulier.py
  requirements.txt
  setup/_metapackage/pyproject.toml
  test-requirements.txt
Labels: 17.0

#807 Syncing from upstream OCA/delivery-carrier (16.0)
  delivery_auto_refresh/i18n/it.po
  stock_picking_report_delivery_cost/i18n/it.po
Labels: 16.0

#810 Syncing from upstream OCA/delivery-carrier (17.0)
  delivery_roulier_option/i18n/it.po
Labels: 17.0

#812 Syncing from upstream OCA/delivery-carrier (16.0)
  delivery_roulier_option/i18n/it.po
Labels: 16.0

#813 Syncing from upstream OCA/delivery-carrier (17.0)
  README.md
  base_delivery_carrier_label/README.rst
  base_delivery_carrier_label/__manifest__.py
  base_delivery_carrier_label/static/description/index.html
  base_delivery_carrier_label/tests/carrier_label_case.py
Labels: 17.0

#814 Syncing from upstream OCA/delivery-carrier (15.0)
  README.md
  delivery_purchase/README.rst
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
Labels: 15.0

#815 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  delivery_purchase/README.rst
  delivery_purchase/__manifest__.py
  delivery_purchase/i18n/delivery_purchase.pot
  delivery_purchase/i18n/es.po
  delivery_purchase/i18n/it.po
  delivery_purchase/models/purchase_order.py
  delivery_purchase/models/stock_picking.py
  delivery_purchase/static/description/index.html
  delivery_purchase/tests/test_delivery_purchase.py
  delivery_purchase/views/purchase_order_view.xml
Labels: 16.0

#816 Syncing from upstream OCA/delivery-carrier (16.0)
  README.md
  sale_order_warehouse_from_delivery_carrier/README.rst
  sale_order_warehouse_from_delivery_carrier/__init__.py
  sale_order_warehouse_from_delivery_carrier/__manifest__.py
  sale_order_warehouse_from_delivery_carrier/i18n/sale_order_warehouse_from_delivery_carrier.pot
  sale_order_warehouse_from_delivery_carrier/models/__init__.py
  sale_order_warehouse_from_delivery_carrier/models/delivery_carrier.py
  sale_order_warehouse_from_delivery_carrier/models/sale_order.py
  sale_order_warehouse_from_delivery_carrier/readme/CONFIGURE.rst
  sale_order_warehouse_from_delivery_carrier/readme/CONTRIBUTORS.rst
  sale_order_warehouse_from_delivery_carrier/readme/DESCRIPTION.rst
  sale_order_warehouse_from_delivery_carrier/readme/USAGE.rst
  sale_order_warehouse_from_delivery_carrier/static/description/icon.png
  sale_order_warehouse_from_delivery_carrier/static/description/index.html
  sale_order_warehouse_from_delivery_carrier/tests/__init__.py
  sale_order_warehouse_from_delivery_carrier/tests/test_module_flow.py
  sale_order_warehouse_from_delivery_carrier/views/delivery_carrier_views.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/sale_order_warehouse_from_delivery_carrier/odoo/addons/sale_order_warehouse_from_delivery_carrier
  setup/sale_order_warehouse_from_delivery_carrier/setup.py
Labels: 16.0

#817 Syncing from upstream OCA/delivery-carrier (17.0)
  README.md
  delivery_state/README.rst
  delivery_state/__init__.py
  delivery_state/__manifest__.py
  delivery_state/data/ir_cron_data.xml
  delivery_state/data/mail_template.xml
  delivery_state/i18n/delivery_state.pot
  delivery_state/i18n/es.po
  delivery_state/i18n/fr.po
  delivery_state/i18n/it.po
  delivery_state/models/__init__.py
  delivery_state/models/delivery_carrier.py
  delivery_state/models/res_company.py
  delivery_state/models/res_config_settings.py
  delivery_state/models/stock_picking.py
  delivery_state/pyproject.toml
  delivery_state/readme/CONFIGURE.md
  delivery_state/readme/CONTRIBUTORS.md
  delivery_state/readme/DESCRIPTION.md
  delivery_state/readme/USAGE.md
  delivery_state/static/description/icon.png
  delivery_state/static/description/index.html
  delivery_state/tests/__init__.py
  delivery_state/tests/test_delivery_state.py
  delivery_state/views/res_config_settings_view.xml
  delivery_state/views/stock_picking_views.xml
  setup/_metapackage/pyproject.toml
Labels: 17.0

#818 Syncing from upstream OCA/delivery-carrier (16.0)
  sale_order_warehouse_from_delivery_carrier/i18n/it.po
Labels: 16.0

#819 Syncing from upstream OCA/delivery-carrier (17.0)
  delivery_state/i18n/it.po
Labels: 17.0
